#=======================================================
# Description: Build OpenWrt using GitHub Actions
# https://github.com/sirliu/AutoBuild-Actions
# Lisence: MIT
# Author: P3TERX,Hyy2001X
# Modify: sirliu
#=======================================================

name: Newifi3

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'

  #schedule:
  #  - cron: 0 11 * * *

  watch:
    types: [started]

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  CONFIG_FILE: newifi3.config
  DIY_SCRIPT: Scripts/AutoBuild_DiyScript.sh
  FUNCTION_SCRIPT: Scripts/AutoBuild_Function.sh
  UPLOAD_RELEASE: true
  UPLOAD_FIRMWARE: true
  UPLOAD_BIN_DIR: false
  REMOVE_OLD_RELEASE: true
  REMOVE_WORKFLOW_RUNS: false
  SEND_MESSAGE_ON_FINISHED: true

jobs:
  BuildOpenWrt:
    runs-on: ubuntu-latest

    steps:
    - name: 检查
      uses: actions/checkout@main
    
    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        df -h
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: 拉取Openwrt源码
      run: |
        git clone -b master $REPO_URL openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: 执行 Diy-Part1 脚本
      run: |
        chmod +x $DIY_SCRIPT
        cd openwrt
        source $GITHUB_WORKSPACE/$DIY_SCRIPT
        source $GITHUB_WORKSPACE/$FUNCTION_SCRIPT && Diy-Part1
        echo "Compile_Date=$(date +%Y%m%d)" > $GITHUB_WORKSPACE/Openwrt.info
        echo "Display_Date=$(date +'%Y/%m/%d')" >> $GITHUB_WORKSPACE/Openwrt.info

    - name: 更新并安装 Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 执行 Diy-Part2 脚本
      run: |
        [ -f $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cd openwrt
        source $GITHUB_WORKSPACE/$DIY_SCRIPT
        source $GITHUB_WORKSPACE/$FUNCTION_SCRIPT && Diy-Part2

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: 下载Packages
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc) V=s
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译Openwrt固件
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 || make -j1 V=s


    - name: 执行 Diy-Part3 脚本
      run: |
        df -h
        echo "## $(date +"%Y%m%d")" > update_log.txt
        cd openwrt
        source $GITHUB_WORKSPACE/$DIY_SCRIPT
        source $GITHUB_WORKSPACE/$FUNCTION_SCRIPT && Diy-Part3
        echo "Artifacts_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: 上传固件到Artifacts
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        name: OpenWrt_Firmware_${{ env.Artifacts_DATE }}
        path: openwrt/bin/Firmware
        
    - name: 上传编译结果目录到 Artifacts
      uses: actions/upload-artifact@main
      if: env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      with:
        name: OpenWrt_bin_${{ env.Artifacts_DATE }}
        path: openwrt/bin

    - name: 上传固件到Releases
      uses: softprops/action-gh-release@v1
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ env.Artifacts_DATE }}_AutoAction
        body_path: update_log.txt
        files: openwrt/bin/Firmware/*
        
    - name: 移除旧的Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.REMOVE_OLD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 移除当前工作流
      uses: GitRML/delete-workflow-runs@main
      if: env.REMOVE_WORKFLOW_RUNS == 'true' && !cancelled()
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: 发送完成通知到微信
      if: env.SEND_MESSAGE_ON_FINISHED == 'true'
      run:
        curl https://sc.ftqq.com/${{ secrets.sckey }}.send?text=OpenWrt编译结束&desp=主人，Action完成了，但是小的不知道是否成功.....
